// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: user.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	ServerStreamingGetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (UserService_ServerStreamingGetUserClient, error)
	ClientStreamingGetUser(ctx context.Context, opts ...grpc.CallOption) (UserService_ClientStreamingGetUserClient, error)
	BidirectionalStreamingGetUser(ctx context.Context, opts ...grpc.CallOption) (UserService_BidirectionalStreamingGetUserClient, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ServerStreamingGetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (UserService_ServerStreamingGetUserClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], "/user.UserService/ServerStreamingGetUser", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceServerStreamingGetUserClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_ServerStreamingGetUserClient interface {
	Recv() (*UserResponse, error)
	grpc.ClientStream
}

type userServiceServerStreamingGetUserClient struct {
	grpc.ClientStream
}

func (x *userServiceServerStreamingGetUserClient) Recv() (*UserResponse, error) {
	m := new(UserResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) ClientStreamingGetUser(ctx context.Context, opts ...grpc.CallOption) (UserService_ClientStreamingGetUserClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[1], "/user.UserService/ClientStreamingGetUser", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceClientStreamingGetUserClient{stream}
	return x, nil
}

type UserService_ClientStreamingGetUserClient interface {
	Send(*UserRequest) error
	CloseAndRecv() (*UserResponse, error)
	grpc.ClientStream
}

type userServiceClientStreamingGetUserClient struct {
	grpc.ClientStream
}

func (x *userServiceClientStreamingGetUserClient) Send(m *UserRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userServiceClientStreamingGetUserClient) CloseAndRecv() (*UserResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UserResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) BidirectionalStreamingGetUser(ctx context.Context, opts ...grpc.CallOption) (UserService_BidirectionalStreamingGetUserClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[2], "/user.UserService/BidirectionalStreamingGetUser", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceBidirectionalStreamingGetUserClient{stream}
	return x, nil
}

type UserService_BidirectionalStreamingGetUserClient interface {
	Send(*UserRequest) error
	Recv() (*UserResponse, error)
	grpc.ClientStream
}

type userServiceBidirectionalStreamingGetUserClient struct {
	grpc.ClientStream
}

func (x *userServiceBidirectionalStreamingGetUserClient) Send(m *UserRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userServiceBidirectionalStreamingGetUserClient) Recv() (*UserResponse, error) {
	m := new(UserResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	GetUser(context.Context, *UserRequest) (*UserResponse, error)
	ServerStreamingGetUser(*UserRequest, UserService_ServerStreamingGetUserServer) error
	ClientStreamingGetUser(UserService_ClientStreamingGetUserServer) error
	BidirectionalStreamingGetUser(UserService_BidirectionalStreamingGetUserServer) error
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) GetUser(context.Context, *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserServiceServer) ServerStreamingGetUser(*UserRequest, UserService_ServerStreamingGetUserServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreamingGetUser not implemented")
}
func (UnimplementedUserServiceServer) ClientStreamingGetUser(UserService_ClientStreamingGetUserServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreamingGetUser not implemented")
}
func (UnimplementedUserServiceServer) BidirectionalStreamingGetUser(UserService_BidirectionalStreamingGetUserServer) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalStreamingGetUser not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ServerStreamingGetUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).ServerStreamingGetUser(m, &userServiceServerStreamingGetUserServer{stream})
}

type UserService_ServerStreamingGetUserServer interface {
	Send(*UserResponse) error
	grpc.ServerStream
}

type userServiceServerStreamingGetUserServer struct {
	grpc.ServerStream
}

func (x *userServiceServerStreamingGetUserServer) Send(m *UserResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _UserService_ClientStreamingGetUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserServiceServer).ClientStreamingGetUser(&userServiceClientStreamingGetUserServer{stream})
}

type UserService_ClientStreamingGetUserServer interface {
	SendAndClose(*UserResponse) error
	Recv() (*UserRequest, error)
	grpc.ServerStream
}

type userServiceClientStreamingGetUserServer struct {
	grpc.ServerStream
}

func (x *userServiceClientStreamingGetUserServer) SendAndClose(m *UserResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userServiceClientStreamingGetUserServer) Recv() (*UserRequest, error) {
	m := new(UserRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _UserService_BidirectionalStreamingGetUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserServiceServer).BidirectionalStreamingGetUser(&userServiceBidirectionalStreamingGetUserServer{stream})
}

type UserService_BidirectionalStreamingGetUserServer interface {
	Send(*UserResponse) error
	Recv() (*UserRequest, error)
	grpc.ServerStream
}

type userServiceBidirectionalStreamingGetUserServer struct {
	grpc.ServerStream
}

func (x *userServiceBidirectionalStreamingGetUserServer) Send(m *UserResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userServiceBidirectionalStreamingGetUserServer) Recv() (*UserRequest, error) {
	m := new(UserRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStreamingGetUser",
			Handler:       _UserService_ServerStreamingGetUser_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStreamingGetUser",
			Handler:       _UserService_ClientStreamingGetUser_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BidirectionalStreamingGetUser",
			Handler:       _UserService_BidirectionalStreamingGetUser_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "user.proto",
}
